! Generated by WorkShop Visual

! Prelude: *module*: resource >>>
! <<< resource ends.

! AppShell
XApplication*AppShell.x: 25
XApplication*AppShell.y: 25

! MainForm

XApplication*MainForm.width: 600
XApplication*MainForm.height: 700
!XApplication*MainForm.width: 60
!XApplication*MainForm.height: 70
XApplication*MainForm.borderWidth: 0
XApplication*MainForm.autoUnmanage: true
XApplication*MainForm.horizontalSpacing: 1
XApplication*MainForm.verticalSpacing: 1
XApplication*MainForm.x: 25
XApplication*Mainform.y: 25

! SplashBulletin

XApplication*SplashBulletin.width: 572
XApplication*SplashBulletin.height: 250
!XApplication*SplashBulletin.width: 200
!XApplication*SplashBulletin.height: 100
XApplication*SplashBulletin.backgroundPixmap: logos/dragon.xpm
! Callgraph

XApplication*Callgraph.background: #dbe6ef
XApplication*DDgraph.background: #dbe6ef

! Flowgraph

! XApplication*Flowgraph.background: #ffffeff6d292
XApplication*Flowgraph.background: #dbe6ef
! CallgraphSlider

XApplication*CallgraphSlider.thumbColor: #758098
XApplication*CallgraphSlider.background: #dbe6ef

! FlowgraphSlider 

XApplication*FlowgraphSlider.thumbColor: #758098
! XApplication*FlowgraphSlider.background: #ffffeff6d292
XApplication*FlowgraphSlider.background: #dbe6ef
! MenuBar
XApplication*MenuBar.packing: PACK_COLUMN

! ProjectCascade

! ProjectMenu
XApplication*ProjectMenu.packing: PACK_COLUMN

! ProjectSeparator1

! OpenMenuButton

! ProjectSeparator2

! ExitMenuButton

! ProjectSeparator3

! AnalysisCascade

! AnalysisMenu
XApplication*AnalysisMenu.entryBorder: 0
XApplication*AnalysisMenu.packing: PACK_COLUMN

! AnalysisSeparator1

! CallgraphMenuButton

! AnalysisSeparator2

! FlowgraphMenuButton

! AnalysisSeparator3

! HelpCascade

! HelpMenu
XApplication*HelpMenu.entryBorder: 0

! HelpSeparator1

! HelpMenuButton

! HelpSeparator2

! MenuBarSeparator

! TopLabel
XApplication*TopLabel.labelString: Source: 

! TopLabelSeparator

! MainPanedWindow
XApplication*MainPanedWindow.width: 600
XApplication*MainPanedWindow.height: 700

! MainScrolledText

! MainHorScrollBar

! MainVertScrollBar

! MainText
XApplication*MainText.height: 500
XApplication*MainText.editable: false
XApplication*MainText.cursorPositionVisible: true

! MessageScrolledText

! MessageHorScrollBar

! MessageVertScrollBar

! MessageText
XApplication*MessageText.editable: false
XApplication*MessageText.cursorPositionVisible: false

! PicGraphForm
XApplication*PicGraphForm.backgroundPixmap: logos/menu.xpm
! GraphShell

! GraphForm

! TopGraphMenuGar

! GraphMenuCascade

! GraphGraphMenu

! GraphMenuSeparator1

! GraphCloseButton

! GraphMenuSeparator2

! GraphHelpMenuCascade

! GraphHelpMenu

! GraphHelpMenuSeparator1

! GraphHelpButton

! GraphHelpMenuSeparator2

! separator8

! GraphPanedWindow

! GraphFormTop

! CallgraphScrolledList

! CallgraphHorScrollBar

! CallgraphVertScrollBar

! CallgraphList

! CallgraphListLabel

! CallgraphLabel

! separator13

! CallgraphForm

! GraphFormBotton

! CFNodeList

! separator14

! ControlFlowScrolledList

! CFHorScrollBar

! CFVertScrollBar

! ControlFlowList

! ControlflowForm

! FlowgraphLabel

! GraphToolForm

! GraphToolTopSeparator

! Generated by WorkShop Visual

! Prelude: *module*: resource >>>
! <<< resource ends.

! CFGraphShell
XApplication*CFGraphShell.title: Dragon Analysis Tool v1.0 - Flowgraph 
Window

! CFGraphForm

! TopCFGraphMenuBar

! CFGraphMenuCascade
XApplication*CFGraphMenuCascade.labelString: Graphs

! CFGraphGraphMenu

! CFGraphMenuSeparator1

! CFGGraphPrintButton
XApplication*CFGraphPrintButton.labelString: Print...

! CFGraphMenuSeparator2

! CFGGraphCloseButton
XApplication*CFGraphCloseButton.labelString: Close

! CFGraphMenuSeparator3

! CFGraphHelpMenuCascade
XApplication*CFGraphHelpMenuCascade.labelString: Help

! CFGraphHelpMenu

! CFGraphHelpMenuSeparator1

! CFGraphHelpButton
XApplication*CFGraphHelpButton.labelString: User's Guide...

! CFGraphHelpMenuSeparator2

! CFGraphToolForm
! XApplication*CFGraphToolForm.backgroundPixmap: slant_right

! CFGraphToolTopSeparator

! CFGmainform

! CFGmenuseparator

XApplication*label1.labelString: Interprocedural Array Region Analysis

! label2
XApplication*label2.labelString: Procedure/Scope  ::  Variable Name,  Usage,  Dimensions,  Number of References                                                                           

! label3
XApplication*label3.labelString:     

! label4
XApplication*label4.labelString:      

! label5
XApplication*label5.labelString:     

! label6
XApplication*label6.labelString:  

! list2

! button2
XApplication*button2.labelString: Close












