/* Generated by wbuild from "Common.w"
** (generator version $Revision: 1.2 $ of $Date: 2004/10/26 18:24:10 $)
*/
#ifndef _XfwfCommon_H_
#define _XfwfCommon_H_
#include <X11/Composite.h>
typedef int  XfAlignment;

#define XfwfCenter 0 


#define XfwfLeft 1 


#define XfwfRight 2 


#define XfwfTop 4 


#define XfwfBottom 8 


#define XfwfTopLeft (XfwfTop +XfwfLeft )


#define XfwfTopRight (XfwfTop +XfwfRight )


#define XfwfBottomLeft (XfwfBottom +XfwfLeft )


#define XfwfBottomRight (XfwfBottom +XfwfRight )


typedef enum {
	    TraverseLeft, TraverseRight, TraverseUp, TraverseDown,
	    TraverseNext, TraversePrev, TraverseHome, TraverseNextTop } TraversalDirection;

void XfwfCallComputeInside(
#if NeedFunctionPrototypes
Widget,Position *,Position *,Dimension *,Dimension *
#endif
);
Dimension  XfwfCallFrameWidth(
#if NeedFunctionPrototypes
Widget
#endif
);
#ifndef XtNtraversalOn
#define XtNtraversalOn "traversalOn"
#endif
#ifndef XtCTraversalOn
#define XtCTraversalOn "TraversalOn"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNhighlightThickness
#define XtNhighlightThickness "highlightThickness"
#endif
#ifndef XtCHighlightThickness
#define XtCHighlightThickness "HighlightThickness"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNhighlightColor
#define XtNhighlightColor "highlightColor"
#endif
#ifndef XtCHighlightColor
#define XtCHighlightColor "HighlightColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNhighlightPixmap
#define XtNhighlightPixmap "highlightPixmap"
#endif
#ifndef XtCHighlightPixmap
#define XtCHighlightPixmap "HighlightPixmap"
#endif
#ifndef XtRPixmap
#define XtRPixmap "Pixmap"
#endif

#ifndef XtNnextTop
#define XtNnextTop "nextTop"
#endif
#ifndef XtCNextTop
#define XtCNextTop "NextTop"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNuserData
#define XtNuserData "userData"
#endif
#ifndef XtCUserData
#define XtCUserData "UserData"
#endif
#ifndef XtRPointer
#define XtRPointer "Pointer"
#endif

typedef struct _XfwfCommonClassRec *XfwfCommonWidgetClass;
typedef struct _XfwfCommonRec *XfwfCommonWidget;
externalref WidgetClass xfwfCommonWidgetClass;
#endif /*_XfwfCommon_H_*/
