/* Generated by wbuild from "Common.w"
** (generator version $Revision: 1.1.1.1 $ of $Date: 2004/08/09 20:03:03 $)
*/
#ifndef _XfwfCommonP_H_
#define _XfwfCommonP_H_
#include <X11/CompositeP.h>
#include <Xfwf/Common.h>
#define max(a, b) ((a )>(b )?(a ):(b ))


#define min(a, b) ((a )<(b )?(a ):(b ))


#define abs(a) ((a )<0 ?-(a ):(a ))


typedef void (*compute_inside_Proc)(
#if NeedFunctionPrototypes
Widget,Position *,Position *,Dimension *,Dimension *
#endif
);
#define XtInherit_compute_inside ((compute_inside_Proc) _XtInherit)
typedef Dimension  (*total_frame_width_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_total_frame_width ((total_frame_width_Proc) _XtInherit)
typedef void (*highlight_border_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_highlight_border ((highlight_border_Proc) _XtInherit)
typedef void (*unhighlight_border_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_unhighlight_border ((unhighlight_border_Proc) _XtInherit)
typedef Boolean  (*would_accept_focus_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_would_accept_focus ((would_accept_focus_Proc) _XtInherit)
typedef void (*traverse_Proc)(
#if NeedFunctionPrototypes
Widget,TraversalDirection ,Widget ,Time *
#endif
);
#define XtInherit_traverse ((traverse_Proc) _XtInherit)
typedef Boolean  (*lighter_color_Proc)(
#if NeedFunctionPrototypes
Widget,Pixel ,Pixel *
#endif
);
#define XtInherit_lighter_color ((lighter_color_Proc) _XtInherit)
typedef Boolean  (*darker_color_Proc)(
#if NeedFunctionPrototypes
Widget,Pixel ,Pixel *
#endif
);
#define XtInherit_darker_color ((darker_color_Proc) _XtInherit)

typedef struct {
/* methods */
compute_inside_Proc compute_inside;
total_frame_width_Proc total_frame_width;
highlight_border_Proc highlight_border;
unhighlight_border_Proc unhighlight_border;
would_accept_focus_Proc would_accept_focus;
traverse_Proc traverse;
lighter_color_Proc lighter_color;
darker_color_Proc darker_color;
/* class variables */
XtTranslations  traversal_trans;
} XfwfCommonClassPart;

typedef struct _XfwfCommonClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
} XfwfCommonClassRec;

typedef struct {
/* resources */
Boolean  traversalOn;
Dimension  highlightThickness;
Pixel  highlightColor;
Pixmap  highlightPixmap;
XtCallbackList  nextTop;
XtPointer  userData;
/* private state */
Boolean  traversal_focus;
GC  bordergc;
} XfwfCommonPart;

typedef struct _XfwfCommonRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
} XfwfCommonRec;

externalref XfwfCommonClassRec xfwfCommonClassRec;

#endif /* _XfwfCommonP_H_ */
