/* Prelude: *module*: header >>> */
/* <<< header ends. */
/*
** Generated by WorkShop Visual
*/
#ifndef _cfgwindow_h
#define _cfgwindow_h

#define XD_MOTIF



extern Widget CFGraphShell;
extern Widget CFGraphForm;
extern Widget TopCFGraphMenuBar;
extern Widget CFGraphMenuCascade;
extern Widget CFGraphGraphMenu;
extern Widget CFGraphMenuSeparator1;
extern Widget CFGGraphPrintButton;
extern Widget CFGraphMenuSeparator2;
extern Widget CFGGraphCloseButton;
extern Widget CFGraphMenuSeparator3;
extern Widget CFGraphHelpMenuCascade;
extern Widget CFGraphHelpMenu;
extern Widget CFGraphHelpMenuSeparator1;
extern Widget CFGraphHelpButton;
extern Widget CFGraphHelpMenuSeparator2;
extern Widget CFGraphToolForm;
extern Widget CFGraphToolTopSeparator;
extern Widget CFGmainform;
extern Widget CFGmenuseparator;
extern Widget CFGFlowgraphLabel;
extern void create_CFGraphShell (Widget, Position, Position);
extern Widget CFGFlowgraphSliderLabel;
extern Widget CFGFlowgraphSlider;
extern Widget CFGZoomOutButton;
extern Widget CFGZoomInButton;

extern void CloseCFGraphWindow(Widget, XtPointer, XtPointer) ;
#endif

