/* Prelude: *module*: header >>> */
/* <<< header ends. */
/*
** Generated by WorkShop Visual
*/

/*
** WorkShop Visual-generated prelude.
** Do not edit lines before "End of WorkShop Visual generated prelude"
** Lines beginning ** WorkShop Visual Stub indicate a stub
** which will not be output on re-generation
*/

/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/PushB.h>

//#include "graphwindow.h"
#include "FGnode.h"

extern FGRAPH cfg;  // HL ++

extern void XDmanage_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDunmanage_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDpopup_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDpopdown_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDmap_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDunmap_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDenable_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDdisable_link( Widget w, XtPointer client_data, XtPointer call_data);

/* End of WorkShop Visual generated prelude */
/*
** WorkShop Visual Stub PrintCFGraphWindow
*/

void PrintCFGraphWindow(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
	cfg.PrintVCG();  //  10/09/02 Huang: invoke xvcg to display the callgraph
}

/*
** WorkShop Visual Stub CloseCFGraphWindow
*/



/*
** WorkShop Visual Stub OpenCFGraphHelp
*/

void OpenCFGraphHelp(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
}

