/* Prelude: *module*: header >>> */
/* <<< header ends. */
/*
** Generated by WorkShop Visual
*/
#ifndef _dragon_h
#define _dragon_h
#define DRAGONPATH "DRAGON_PATH"

#include "UIClasses.h"
#include "regions.h"
extern Widget AppShell;
extern Widget MainForm;
extern Widget MenuBar;
extern Widget ProjectCascade;
extern Widget ProjectMenu;
extern Widget ProjectSeparator1;
extern Widget OpenMenuButton;
extern Widget ProjectSeparator2;
extern Widget ExitMenuButton;
extern Widget ProjectSeparator3;
extern Widget AnalysisCascade;
extern Widget AnalysisMenu;
extern Widget AnalysisSeparator1;
extern Widget CallgraphMenuButton;
extern Widget AnalysisSeparator2;
extern Widget FlowgraphMenuButton;
extern Widget AnalysisSeparator3;
extern Widget HelpCascade;
extern Widget HelpMenu;
extern Widget HelpSeparator1;
extern Widget HelpMenuButton;
extern Widget HelpSeparator2;
extern Widget MenuBarSeparator;
extern Widget TopLabel;
extern Widget TopLabelSeparator;
extern Widget MainPanedWindow;
extern Widget MainScrolledText;
extern Widget MainHorScrollBar;
extern Widget MainVertScrollBar;
extern Widget MainText;
extern Widget MessageScrolledText;
extern Widget MessageHorScrollBar;
extern Widget MessageVertScrollBar;
extern Widget MessageText;


extern UIGraphNode *UICallgraphRoot;
extern vector<regions> UIRegions;
extern vector<pregions> UIPregions;
extern int rootnode;
extern void create_AppShell (Display *, char *, int, char **);
extern void OpenFile(char *Filename);
extern void HighlightLine(unsigned long);
extern void UnHighlightText(void);
extern void HighlightLines(vector<unsigned int>line_nums, int len);
extern void PrintMessage(char Message[]);
extern vector<unsigned long> TextPos;
#define ArcForeground "Black" //edge default foreground
extern bool CGwindowopen;
extern bool FGwindowopen;
extern bool FSwindowopen;
extern bool ProgramActive;
extern bool RootNodeDetected;
extern bool DDwindowopen;
extern bool Regionswindowopen;
extern char * SelectedFile;
extern unsigned int CGfdback;
#endif







