/*
** Generated by WorkShop Visual
*/
/*For call graph display*/
#ifndef _graphwindow_h
#define _graphwindow_h

#define XD_MOTIF
#include "XmGraph/Graph.h"


extern Widget GraphShell;
extern Widget GraphForm;
extern Widget TopGraphMenuGar;
extern Widget GraphMenuCascade;
extern Widget GraphGraphMenu;
extern Widget DynamicGraphButtion;
extern Widget GraphMenuSeparator1;
extern Widget GraphMenuSeparator1d;
extern Widget GraphCloseButton;
extern Widget GraphMenuSeparator2;
extern Widget GraphHelpMenuCascade;
extern Widget GraphHelpMenu;
extern Widget GraphHelpMenuSeparator1;
extern Widget GraphHelpButton;
extern Widget GraphHelpMenuSeparator2;
extern Widget GraphPanedWindow;
extern Widget GraphFormTop;
extern Widget CallgraphScrolledList;
extern Widget CallgraphVertScrollBar;
extern Widget CallgraphList;
extern Widget CallgraphListLabel;
extern Widget CallgraphLabel;
extern Widget CallgraphForm;
extern Widget GraphFormBotton;
extern Widget CFNodeList;
extern Widget ControlFlowScrolledList;
extern Widget CFVertScrollBar;
extern Widget ControlFlowList;
extern Widget ControlflowForm;
extern Widget FlowgraphLabel;
extern Widget GraphToolForm;
extern Widget GraphToolTopSeparator;
extern Widget Flowgraph;
extern Widget ZoomOutButton;
extern Widget ZoomInButton;
extern Widget PicGraphForm;
extern int ProcedureLoaded;
extern void create_GraphShell (Widget,Position,Position);
void AvoidNew(Widget graph_part, XtPointer client, XmGraphCallbackStruct *calldata);
void MoveHandling(Widget GraphWidget, XtPointer client, XmGraphCallbackStruct *calldata);
extern void LoadStatement(Widget w, XtPointer client, XtPointer Calldata);
extern void CreateFlowgraph(int NodeNum);
extern void SliderScroll(Widget Slider, Widget Parent, XfwfScrollInfo *calldata);
extern void CloseGraphWindow(Widget, XtPointer, XtPointer) ;
extern Widget CreateANode(Widget GraphWidget, char NodeLabel[]);
extern Widget CreateAnEdge(Widget GraphWidget, char NodeLabel[], Widget SuperNode,char edgeLabel[]); 
extern Widget CreateAnEdgeDD(Widget GraphWidget, char NodeLabel[], Widget SuperNode,char edgeLabel[], char color[]);
extern void ColorWidget(Widget w, char color[],bool bg);
extern char *itoa(int i);
#endif



